publish_to: https://pub.dev

name: text_expressions
version: 1.1.0

description: >-
  Tiny, simple and complete tool to supercharge your string files
  with dynamic user-defined expressions.

homepage: https://github.com/wordcollector/text_expressions
repository: https://github.com/wordcollector/text_expressions
issue_tracker: https://github.com/wordcollector/text_expressions/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  enum_as_string: ^1.0.0
  sprint: ^1.0.2+3

dev_dependencies:
  words: ^0.0.1+2