publish_to: https://pub.dev

name: text_expressions
version: 1.1.0+1

description: >-
  A tiny, simple and complete tool to supercharge static JSON strings
  with the power of dynamic, user-defined expressions. â€“ Ensure your
  translations are always grammatically and orthographically correct.

homepage: https://github.com/wordcollector/text_expressions
repository: https://github.com/wordcollector/text_expressions
issue_tracker: https://github.com/wordcollector/text_expressions/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  enum_as_string: ^1.0.0+2
  sprint: ^1.0.2+3

dev_dependencies:
  words: ^2.0.0+1
